version: 0.2
phases:
  build:
    commands:
      - tar -zcvf s3.tar.gz s3.yml
      - tar -zcvf sqs.tar.gz sqs.yml
      - aws s3 cp ./ s3://dpellerin-pipeline-storage/ --recursive --exclude "*" --include "*.tar.gz"
