version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
      python: 3.8
    commands:
      - gem install cfn-nag
      - pip install --upgrade pip
      - pip install cfn-lint
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - cfn-lint ./cfn/*.yml
      - cfn_nag_scan --output-format txt --input-path ./cfn
      - tar -vczf "myapp-ci-$CODEBUILD_BUILD_ID.zip" ./cfn/*.yml
      - aws s3 cp "myapp-ci-$CODEBUILD_BUILD_ID.zip" s3://dpellerin-pipeline-storage/
