version: 0.2
env:
  parameter-store:
    OXR_APP_ID: "/staging/OXR_APP_ID"
phases:
  build:
    commands:
      - aws s3 cp ./ s3://dpellerin-pipeline-storage/ --recursive --exclude "*" --include "cfn/*.yml"
