version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
      python: 3.8
    commands:
      - gem install cfn-nag
      - pip install --upgrade pip
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint ./cfn/*.yml
      - cfn_nag_scan --output-format txt --input-path ./cfn
      - zip -r "myapp-ci-$CODEBUILD_BUILD_NUMBER.zip" ./cfn/*.yml
      - aws s3 cp "myapp-ci-$CODEBUILD_BUILD_NUMBER.zip" s3://dpellerin-pipeline-storage/
      - aws s3 cp "myapp-ci-$CODEBUILD_BUILD_NUMBER.zip" s3://dpellerin-pipeline-storage/latest.zip
