AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  QueueName:
    Type: String
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: 'alias/aws/sqs'
      QueueName: !Ref QueueName
